# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/r8qxx/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/r8qxx

PRODUCT_COPY_FILES += \
    vendor/samsung/r8qxx/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/samsung/r8qxx/proprietary/vendor/firmware/nfc/libsn100u_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libsn100u_fw.so

PRODUCT_PACKAGES += \
    ese_spi_nxp \
    android.hardware.secure_element@1.0-service
