# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/r8q-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r8qxx r8qxxx,$(TARGET_DEVICE)),)

endif
