# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/r8q/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/r8q

PRODUCT_COPY_FILES += \
    vendor/samsung/r8q/proprietary/vendor/etc/init/android.hardware.secure_element@1.0-service-gto-sku.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.0-service-gto-sku.rc \
    vendor/samsung/r8q/proprietary/vendor/etc/init/android.hardware.secure_element@1.0-service-sku.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.0-service-sku.rc \
    vendor/samsung/r8q/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/samsung/r8q/proprietary/vendor/etc/libse-gto-hal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libse-gto-hal.conf \
    vendor/samsung/r8q/proprietary/vendor/firmware/nfc/libsn100u_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libsn100u_fw.so

PRODUCT_PACKAGES += \
    android.hardware.secure_element-impl-gto \
    ese_spi_nxp \
    android.hardware.secure_element@1.0-service \
    android.hardware.secure_element@1.0-service-gto
